### ISSUE TITLE
Can `ddbug_parser::File::parse` return a `ddbug::File` object?

### ISSUE THREAD

**Issue by ice-tong** [gimli-rs/ddbug#26]
Hi, the `ddbug_parser` is very nice and useful for me. Thanks for your work!

I meet trouble when I try to code with ddbug_parser. I want to implement a method that can return dwarf variable information of the given variable location (function address with CFA address / global address/register/register offset).

It seems that I cant hold `ddbug_parser::File` once `ddbug_parser::File::parse` finished. Are there any solutions or suggestions?

**Comment by philipc** [comment]
That's a limitation of the current API sorry. It's written this way because rust doesn't support self-referential structs without using `unsafe` code. We can probably fix this with only a small amount of `unsafe` code. For example, [this code in backtrace-rs](https://github.com/rust-lang/backtrace-rs/blob/be161a12d093c1896adce2bfdf4aa8e9059ea023/src/symbolize/gimli.rs#L57-L103) is solving this problem.

**Comment by ice-tong** [comment]
Hi, philipc. I'm happy with your quick reply!

I'm new to Rust, lifetime is a novelty thing for me. I will read the example code in backtrace-rs, and try to solve this problem by introducing some `unsafe` code.

Thanks for your kindly help!

**Comment by philipc** [comment]
Fixed in e4a6d632a861f5d0fba36ce1988000456893d476

**Comment by ice-tong** [comment]
nice work!
